services:
  # the proxy that guards docker.sock for the host
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1   # allow starting/stopping/creating containers
      - POST=1         # allow creating containers
      - GET=1          # allow inspecting containers/images
      - EXEC=0         # block dangerous exec calls on host containers
      - VOLUMES=0      # block mounting host volumes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  # jae slack bot / execution server
  jae-server:
    image: jae-exec-server
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375
    depends_on:
      - docker-proxy
    ports:
      - "6200:6200/tcp"
    volumes:
      - ./execution_server/web:/home/runner/web:ro
      - ./execution_server/static:/home/runner/static:ro